import type { Metadata } from "next";
import { absoluteUrl } from "@/lib/site";

export const metadata: Metadata = {
  title: "Kebijakan Privasi — Qira",
  description: "Kebijakan privasi Qira dan cara aplikasi menangani data pengguna.",
  alternates: { canonical: "/privacy-policy" },
  openGraph: { title: "Kebijakan Privasi — Qira", description: "Kebijakan privasi Qira dan cara aplikasi menangani data pengguna.", url: absoluteUrl("/privacy-policy"), type: "website" },
};

export default function PrivacyPolicyPage() {
  return <div className="container py-10 sm:py-16"><article className="mx-auto max-w-3xl"><p className="text-sm font-bold uppercase tracking-[.18em] text-[var(--blue)]">Privasi</p><h1 className="mt-3 text-3xl font-bold sm:text-4xl">Kebijakan Privasi Qira</h1><p className="mt-4 text-sm text-[var(--muted)]">Terakhir diperbarui: 25 Juli 2026</p><div className="mt-8 space-y-8 text-sm leading-7 text-[var(--muted)]"><section><h2 className="text-xl font-bold text-[var(--ink)]">Ringkasan</h2><p className="mt-3">Qira dibuat sebagai aplikasi Quran yang ringan. Qira tidak memerlukan akun, tidak menggunakan database pengguna, dan tidak menjual data pribadi.</p></section><section><h2 className="text-xl font-bold text-[var(--ink)]">Data yang disimpan di perangkat</h2><p className="mt-3">Untuk menyediakan fitur dasar, Qira dapat menyimpan preferensi ringan di localStorage browser Anda, seperti posisi terakhir membaca, bookmark ayat, pilihan qari, lokasi jadwal shalat, dan aktivitas bacaan harian.</p><p className="mt-3">Data tersebut tersimpan di perangkat dan browser Anda. Qira tidak mengirimkannya ke server Qira untuk membuat akun atau sinkronisasi cloud.</p></section><section><h2 className="text-xl font-bold text-[var(--ink)]">Layanan pihak ketiga</h2><p className="mt-3">Qira menggunakan EQuran API untuk mengambil data surah, ayat, audio, tafsir, dan jadwal shalat. Permintaan ke layanan tersebut dapat membawa informasi teknis standar yang diperlukan oleh jaringan dan layanan API.</p><p className="mt-3">Qira tidak mengontrol kebijakan privasi layanan pihak ketiga. Silakan merujuk pada kebijakan mereka untuk informasi lebih lanjut.</p></section><section><h2 className="text-xl font-bold text-[var(--ink)]">Berbagi dan analitik</h2><p className="mt-3">Qira tidak menyediakan login, komentar, feed sosial, cloud sync, atau layanan analitik perilaku dalam aplikasi ini. Jika Anda menggunakan fitur berbagi ayat, browser dapat menampilkan dialog berbagi atau menyalin tautan sesuai kemampuan perangkat Anda.</p></section><section><h2 className="text-xl font-bold text-[var(--ink)]">Menghapus data lokal</h2><p className="mt-3">Anda dapat menghapus data Qira melalui pengaturan site data atau localStorage pada browser. Menghapus data tersebut akan menghapus bookmark, posisi terakhir, preferensi qari, lokasi shalat, dan aktivitas bacaan yang tersimpan di perangkat.</p></section><section><h2 className="text-xl font-bold text-[var(--ink)]">Perubahan kebijakan</h2><p className="mt-3">Kebijakan ini dapat diperbarui apabila fitur atau cara kerja Qira berubah. Versi terbaru akan ditampilkan di halaman ini.</p></section></div></article></div>;
}
